### ISSUE TITLE
TF name/symbol(s) regexp/parsing bug

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/msigdb-to-biopax#5]
A (very old) regexp/parsing bug caused some of known TFs were lost (not recognised, not set as controllers for the corresponding template reactions). E.g., from -

`DESCRIPTION_BRIEF="Genes with promoter regions [-2kb,2kb] around transcription start site containing the motif SGCGSSAAA which matches annotation for E2F1: E2F transcription factor 1&lt;br&gt; TFDP1: transcription factor Dp-1&lt;br&gt; RB1: retinoblastoma 1 (including osteosarcoma)"`

The converter extracts only "RB1" (the last symbol) instead of expected "E2F1" and makes RB1 be controller for TRRs (template reaction regulation), which is probably wrong, for RB1 is known as co-factor but not a TF itself (it e.g., binds to and inhibits E2F1 which binds DNAs...)

This refs (and partially causes) PathwayCommons/cpath2#284 
So, looks, we have to yet understand what the description above means and how to parse it, besides using E2F1 as TF (controller)... 
Attn: @ozgunbabur

**Comment by ozgunbabur** [comment]
In this example, all three TFs should be separate controllers. There is not
enough information to build a detailed control model. Normally, E2F1 and
TFDP1 works together to activate transcription, and RB1 inhibits them by
binding, unless it is phosphorylated. In this text we have actors but no
logic of action.

**Comment by IgorRodchenkov** [comment]
This fixed version will be used to generate the input BioPAX data next time (for the PC v10 service) unless we replace it with a new TRANSFAC converter.
